#!/usr/bin/env python3
"""Export a compact Swift exemplar bank for PDF shape recognition."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def distance(a: tuple[float, float], b: tuple[float, float]) -> float:
    return math.hypot(a[0] - b[0], a[1] - b[1])


def polyline_length(points: list[tuple[float, float]]) -> float:
    return sum(distance(points[index - 1], points[index]) for index in range(1, len(points)))


def resample(points: list[tuple[float, float]], count: int = 64) -> list[tuple[float, float]]:
    if len(points) < 2:
        return points
    total = max(polyline_length(points), 1.0)
    interval = total / (count - 1)
    result = [points[0]]
    previous = points[0]
    distance_since_last = 0.0
    index = 1
    while index < len(points):
        current = points[index]
        segment = distance(previous, current)
        if distance_since_last + segment >= interval and segment > 0.001:
            ratio = (interval - distance_since_last) / segment
            next_point = (
                previous[0] + (current[0] - previous[0]) * ratio,
                previous[1] + (current[1] - previous[1]) * ratio,
            )
            result.append(next_point)
            previous = next_point
            distance_since_last = 0.0
        else:
            distance_since_last += segment
            previous = current
            index += 1
    while len(result) < count:
        result.append(points[-1])
    return result[:count]


def normalize(points: list[tuple[float, float]], count: int = 64) -> list[tuple[float, float]]:
    sampled = resample(points, count)
    center_x = sum(point[0] for point in sampled) / len(sampled)
    center_y = sum(point[1] for point in sampled) / len(sampled)
    translated = [(x - center_x, y - center_y) for x, y in sampled]
    first_x, first_y = translated[0]
    angle = -math.atan2(first_y, first_x)
    cos_a = math.cos(angle)
    sin_a = math.sin(angle)
    rotated = [(x * cos_a - y * sin_a, x * sin_a + y * cos_a) for x, y in translated]
    scale = max(
        max(abs(x) for x, _ in rotated),
        max(abs(y) for _, y in rotated),
        1.0,
    )
    return [(x / scale, y / scale) for x, y in rotated]


def load_records(path: Path) -> list[tuple[str, list[tuple[float, float]]]]:
    records: list[tuple[str, list[tuple[float, float]]]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        record = json.loads(line)
        expected = record.get("expectedKind")
        raw_points = record.get("rawPoints", [])
        if not expected or len(raw_points) < 2:
            continue
        points = [(float(point["x"]), float(point["y"])) for point in raw_points]
        records.append((expected, points))
    return records


def swift_float(value: float) -> str:
    return f"{value:.3f}"


def write_swift(records: list[tuple[str, list[tuple[float, float]]]], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by scripts/export_shape_exemplar_bank.py.",
        "// Source samples combine public Quick, Draw! vectors with synthetic note-shape augments.",
        "// Do not edit this file by hand; regenerate it from the replay corpus instead.",
        "import Foundation",
        "",
        "enum PDFShapeExemplarBank {",
        "    struct Exemplar {",
        "        let kind: String",
        "        let points: [Float]",
        "    }",
        "",
        "    static let pointCount = 64",
        "    static let exemplars: [Exemplar] = [",
    ]
    for kind, points in records:
        normalized = normalize(points)
        flat = ", ".join(
            swift_float(value)
            for point in normalized
            for value in point
        )
        lines.append(f'        Exemplar(kind: "{kind}", points: [{flat}]),')
    lines.extend([
        "    ]",
        "}",
        "",
    ])
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument(
        "--output",
        default="apps/client/apple/Sources/Codmes/PDFShapeExemplarBank.swift",
    )
    args = parser.parse_args()
    records = load_records(Path(args.input))
    if not records:
        raise SystemExit(f"no labeled records found in {args.input}")
    write_swift(records, Path(args.output))
    print(f"wrote {len(records)} exemplars to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
